/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2019-12-15 16:41:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import bbs.Bbs;
import bbs.BbsDAO;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bbs.Bbs");
    _jspx_imports_classes.add("bbs.BbsDAO");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" initial-scale=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("ul, li {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main ul {\r\n");
      out.write("\tbackground-color: #dfdfdf;\r\n");
      out.write("\tborder: 1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main>ul {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main>ul>li {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tborder: 1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main li>a {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main li:hover>a {\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main li {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main ul ul {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 100%;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main li>ul>li {\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main li:hover>ul {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\tcolor: inherit;\r\n");
      out.write("\ttext-decoration: inherit;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>자취세끼</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-default \">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\taria-expaned=\"false\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"Main.jsp\">자취세끼</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");

if( (String)session.getAttribute("userEmail") == null) 
 {
      out.write("\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\tid=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li><a href=\"Login.jsp\">로그인</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"Join.jsp\">회원가입</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li>로그인 해주세요</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
 }else { 
      out.write("\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\"\r\n");
      out.write("\t\t\tid=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li><a href=\"BBS.jsp\">레시피</a></li>\r\n");
      out.write("\t\t\t\t<li><a>게시판</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"LogoutAction.jsp\">로그아웃</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li>");
      out.print((String)session.getAttribute("userEmail")+ "이 로그인 되었습니다." );
      out.write("</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
 }
      out.write("\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<form action=\"#\" method=\"post\"\r\n");
      out.write("\t\t\tstyle=\"display: flex; justify-content: center;\">\r\n");
      out.write("\t\t\t<a href=\"Main.jsp\"><img src=\"image/img1.png\" width=\"100\"\r\n");
      out.write("\t\t\t\theight=\"100\"></a> <input type=\"text\" placeholder=\"내용을 입력해주세요\"\r\n");
      out.write("\t\t\t\tstyle=\"border-radius: 5px; border =1; height: 40px; width: 220px; position: relative; top: 30px;\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"검색\"\r\n");
      out.write("\t\t\t\tstyle=\"border-radius: 5px; border: none; height: 40px; width: 100px; position: relative; top: 30px;\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"main\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"Main.jsp\">홈</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"BBS.jsp\">레시피</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">간단 음식</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">국/탕</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">술안주</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"BBS.jsp\">게시판</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">인천</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">서울</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"Map.jsp\">찾아오는길 </a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h1 style=\"display: flex; justify-content: center\">자취세끼 추천 레시피</h1>\r\n");
      out.write("\t\t<div style=\"display: flex; justify-content: space-around;\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t");
 
				BbsDAO BbsDAO = new BbsDAO(); 
				String path = application.getRealPath("/upload/");
				int i=1;
				String SQL = "SELECT * FROM Recipe where RecipeAvailable=1";
				try {
					String dbURL = "jdbc:oracle:thin:@localhost:1521:XE";
					String dbID = "a201645006";
					String dbPassword = "manager";
					Class.forName("oracle.jdbc.driver.OracleDriver");
					Connection conn = DriverManager.getConnection(dbURL, dbID, dbPassword);
					PreparedStatement pstmt = conn.prepareStatement(SQL);
					ResultSet rs = pstmt.executeQuery();
					Bbs bbs = new Bbs();
					while (rs.next()) {
						if (i > 3) {
							break;
						}
						bbs.setRecipeID(rs.getInt(1));
						bbs.setRecipeTitle(rs.getString(2));
						bbs.setUserEmail(rs.getString(3));
						bbs.setFileRealName(rs.getString(4));
						bbs.setFilepath(rs.getString(5));
						bbs.setRecipeDate(rs.getString(6));
						bbs.setRecipeContent(rs.getString(7));
						bbs.setRecipeAvailable(rs.getInt(8));
				
      out.write("\r\n");
      out.write("\t\t\t\t<li style=\"border: 1px solid black; display: inline-block;\"><a\r\n");
      out.write("\t\t\t\t\thref=\"View.jsp?recipeID=");
      out.print(bbs.getRecipeID());
      out.write("\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.print(path + "/" + bbs.getFileRealName());
      out.write("\" width=\"120\"\r\n");
      out.write("\t\t\t\t\t\theight=\"100\"></a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"border-top: 1px solid black; text-align: center;\">");
      out.print(bbs.getRecipeTitle());
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t");

				}
					rs.close();
					pstmt.close();
					conn.close();
				} catch (Exception e) {
					e.printStackTrace();
				}
				
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h1 style=\"display: flex; justify-content: center;\">자취세끼 추천 맛집</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"height: 250px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li style=\"display: inline-block; font-size: 12;\">대표 : 이종건 /\r\n");
      out.write("\t\t\t\tEmail:ex924097@naver.com / F : 032)870-2114<br> 인천광역시 미추홀구\r\n");
      out.write("\t\t\t\t인하로100인하공업전문대학<br> 문의전화(운영시간 평일 10:00~18:00)<br> 서비스 이용문의\r\n");
      out.write("\t\t\t\t:010-2231-7425<br> <br> (주)자취세끼\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li style=\"display: inline-block;\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"https://twitter.com/\"><img src=\"image\\bird.PNG\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"display: inline-block;\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"https://www.youtube.com/\"><img src=\"image\\youtube.PNG\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"display: inline-block;\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"https://www.facebook.com/\"><img src=\"image\\facebook.PNG\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"display: inline-block;\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"https://www.instagram.com/\"><img src=\"image\\instar.PNG\"></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li style=\"display: inline-block; float: right;\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea cols=\"40\" rows=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"회원님들의 의견을 자취세끼에게 알려주세요\" style=\"font-size: 12;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"display: flex; justify-content: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"의견제출\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"display: flex; justify-content: center; width: 305; height: 30; border: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
